batch_size: 28
train_steps: 200
context length: 250
num_tasks: 25
output_dir: ../outputs/GPT2/240619_210806.2079cd_upperTriA_gauss_C
checkpoint_callback /home/sultand/mop_modifications/streamlined_mop/outputs/GPT2/240619_210806.2079cd_upperTriA_gauss_C/checkpoints
ckpt_path: ../outputs/GPT2/240619_210806.2079cd_upperTriA_gauss_C/checkpoints/step=200.ckpt
Traceback (most recent call last):
  File "/home/sultand/mop_modifications/streamlined_mop/src/data_train.py", line 122, in <module>
    train_gpt2(model, config, output_dir) # train the model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sultand/mop_modifications/streamlined_mop/src/train.py", line 50, in train_gpt2
    trainer = pl.Trainer(
              ^^^^^^^^^^^
  File "/home/sultand/.conda/envs/mop/lib/python3.12/site-packages/pytorch_lightning/utilities/argparse.py", line 70, in insert_env_defaults
    return fn(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^
TypeError: Trainer.__init__() got an unexpected keyword argument 'gpus'